[versions]
jchucomponents = "2.0.0-dev3"
agp = "8.4.2"
kotlin = "2.0.0"
dokka = "1.9.20"
androidx-activity = "1.9.0"
androidx-compose = "1.6.8"
androidx-lifecycle = "2.8.2"
androidx-navigation = "2.7.7"
com-google-accompanist = "0.32.0"
com-squareup-okhttp3 = "4.12.0"
com-squareup-retrofit2 = "2.11.0"
coil-kt = "2.6.0"
coil-gif = "2.5.0"
org-jetbrains-kotlin = "2.0.0"
org-jetbrains-kotlinx = "1.8.1"

[libraries]
androidx-datastore = "androidx.datastore:datastore-preferences:1.1.1"
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-browser = "androidx.browser:browser:1.8.0"
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "androidx-compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-foundation-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-material-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose" }
androidx-compose-material3 = "androidx.compose.material3:material3:1.2.1"
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-core-core-ktx = "androidx.core:core-ktx:1.13.1"
androidx-core-core-splashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx-lifecycle-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-livedata-core-ktx = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-preference = "androidx.preference:preference-ktx:1.2.1"
com-google-accompanist-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "com-google-accompanist" }
com-google-android-gms-play-services-base = "com.google.android.gms:play-services-base:18.5.0"
com-google-code-gson = "com.google.code.gson:gson:2.11.0"
com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3" }
com-squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "com-squareup-okhttp3" }
com-squareup-retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "com-squareup-retrofit2" }
com-squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "com-squareup-retrofit2" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-kt" }
org-jetbrains-kotlinx-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
org-jetbrains-kotlinx-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx" }
androidx-appcompat = "androidx.appcompat:appcompat:1.7.0"
revenuecat = "com.revenuecat.purchases:purchases:6.9.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "org-jetbrains-kotlin" }

[bundles]
core-androidx = [
    "androidx-core-core-ktx",
    "androidx-lifecycle-lifecycle-livedata-core-ktx",
    "androidx-lifecycle-lifecycle-viewmodel-ktx",
]
core-jetbrains = [
    "org-jetbrains-kotlinx-kotlinx-coroutines-android",
    "org-jetbrains-kotlinx-kotlinx-coroutines-core",
]
core-squareup = [
    "com-squareup-okhttp3-logging-interceptor",
    "com-squareup-retrofit2-converter-gson",
    "com-squareup-retrofit2-retrofit",
]
# FOR JCHUCOMPONENTS KTX
ktx-androidx = [
    "androidx-browser",
    "androidx-navigation-navigation-compose",
]
ktx-google = [
    "com-google-android-gms-play-services-base",
    "com-google-code-gson",
]

# FOR JCHUCOMPONENTS QR
qr-androidx = [
    "androidx-core-core-ktx"
]
qr-third-party = [
    "com-squareup-okhttp3-okhttp",
]
# FOR JCHUCOMPONENTS UI
ui-accompanist = [
    "com-google-accompanist-accompanist-systemuicontroller",
]
ui-androidx = [
    "androidx-core-core-splashscreen",
]
ui-compose = [
    "androidx-activity-activity-compose",
    "androidx-compose-animation",
    "androidx-compose-foundation",
    "androidx-compose-foundation-foundation-layout",
    "androidx-compose-material",
    "androidx-compose-material-material-icons-extended",
    "androidx-compose-material3",
    "androidx-compose-runtime",
    "androidx-compose-ui",
    "androidx-compose-ui-ui-tooling",
    "androidx-navigation-navigation-compose",
    "coil-compose",
]
# FOR JCHUCOMPONENTS PAY
pay-android = [
    "revenuecat",
]
pay-jetbrains = [
    "org-jetbrains-kotlinx-kotlinx-coroutines-android",
    "org-jetbrains-kotlinx-kotlinx-coroutines-core",
]

# FOR JCHUCOMPONENTS PREFERENCES
preferences-androidx = [
    "androidx-datastore",
    "androidx-preference",
    "androidx-lifecycle-lifecycle-runtime-compose",
]
preferences-google = [
    "com-google-code-gson",
]
preferences-compose = [
    "androidx-compose-runtime",
    "androidx-compose-ui",
]